### ISSUE TITLE
add a few fields to iTunes module

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome-modules#11]
<pre>=== This issue was migrated from JIRA ===
Type: New Feature
Priority: Major
Status: Open
Resolution: Unresolved
Reported by: Kevin Horan
Assigned to: Robert Cooper
Created: Fri Dec 28 05:25:09 CET 2012
Updated: Fri Dec 28 05:25:09 CET 2012
JIRA Link: <a href="https://rometools.jira.com/browse/MODULES-10">https://rometools.jira.com/browse/MODULES-10</a>
=========================================</pre>
<p>I have been using your iTunes module to develop a podcast. There <br/>
are a few fields I would like to use though that aren't present, at the <br/>
Entry level. These are the "image" tag (A URL), the "order" tag (an <br/>
int), and the ability to set "explicit" to "clean" (makes iTunes display <br/>
a certain icon I guess). The following two tags would also be useful, <br/>
but not required: "complete" (Boolean), and "new-feed-url" (URL).<br/>
     I'd be happy to makes these changes myself. I'm not <br/>
very familiar with contributing to projects, so let me know how best to <br/>
help.</p>

**Comment by claym** [comment]
Were these changes ever merged? I have need of the image tag support.

**Comment by mishako** [comment]
Most of this has been recently fixed in #37, except for the `clean` value of the `explicit` tag.

Adding `clean` value is a breaking change. I don't want to do breaking changes without a roadmap and a separate branch for the next major version. Otherwise any merged change will end up in the next minor or patch release.

By the way, maybe it's time to do a minor release? What do you think? @snoopdave @PatrickGotthard

**Comment by mishako** [comment]
@PatrickGotthard Any thoughts on doing a minor release?

**Comment by mishako** [comment]
Moved this issue to https://github.com/rometools/rome/issues/244 as part of https://github.com/rometools/rome/issues/217
