### ISSUE TITLE
ROME MediaRSS not handling old namespace

### ISSUE THREAD

**Issue by guw** [rometools/rome-modules#33]
I just run into a system consuming my feed and looking for the old (still current?) namespace declaration.

Looking at http://www.rssboard.org/media-rss I found the following at the top of the document:
> Editor's Note: This is a draft document that is still being proofread during the transition of Media RSS from Yahoo to the RSS Advisory Board. The official specification is at http://video.search.yahoo.com/mrss until this notice has been removed. This is version 1.5.1 of the Media RSS specification, a namespace for RSS 2.0 published on Dec. 11, 2009. The current version always will be available at this link. Public comments are welcomed at RSS-Media.

Should ROME support generating and/or parsing the old namespace?

**Comment by mishako** [comment]
@guw I don't see where the text you're citing suggests that there is or was another namespace for MRSS. The link seems just to be pointing to the official specification (which is not there, but that's another question).

**Comment by guw** [comment]
Yeah, the Yahoo links seems broken.

Here is what I mean:
https://github.com/guw/rome-extensions/blob/master/src/main/java/io/guw/rometools/mrss/MediaModuleWithOldNamespaceConstants.java

**Comment by mishako** [comment]
@guw But how do you know that there once was a namespace "http://video.search.yahoo.com/mrss"?

**Comment by guw** [comment]
It's right there in the editor's note of the new spec. 

> The official specification is at http://video.search.yahoo.com/mrss until this notice has been removed.

There is also an old discussion here:
https://groups.yahoo.com/neo/groups/rss-media/conversations/topics/1202

**Comment by mishako** [comment]
@guw 
That "http://video.search.yahoo.com/mrss" in the editor's note is not a namespace. It's a URL pointing to the specification website, which is not the same thing.

From the discussion you linked:
> On behalf of Yahoo!, I would like to re-state that the namespace change sometime back was accidental , we apologize for it and that it has been *corrected* now.

So, the change was accidental. I think we shouldn't support accidental namespaces. Besides, we don't know how exactly the accidental namespace looked like.

**Comment by guw** [comment]
As stated in my first comment. I actually ran into an issue with a system expecting the old namespace. I'm also not entirely sure that the link in the editor's note is only a link. It's an url and co-incidentally it's how the accidental namespace looks (adding a trailing slash) like and what made the other system happy.

Anyway, I was able to work around it by providing an extension to Rome. It's a workaround but it works.

**Comment by mishako** [comment]
@guw
The fact that there is a system that expects a wrong namespace is not a good reason for supporting it.

> I'm also not entirely sure that the link in the editor's note is only a link.

The editor's note doesn't call it namespace. Isn't that enough reason to not think it is a namespace?

> It's an url and co-incidentally it's how the accidental namespace looks.

Yes, it's a URL, because it's a link to the specification. Doesn't make it a namespace though. It does look like the accidental namespace because Yahoo engineers made a mistake. They moved specification from one address (http://search.yahoo.com/mrss) to another (http://video.search.yahoo.com/mrss) and one of the Yahoo engineers replaced the namespace in the actual specification text. Presumably because he didn't understand the difference between specification website URL and XML namespace. They quickly corrected it though and it has never been a part of any Media RSS spec's version. So I would challenge your statement that http://video.search.yahoo.com/mrss/ is the _old_ namespace. The current one (http://search.yahoo.com/mrss/) has been there before and after the accident. So it is both the old and the new. Accidental one (http://video.search.yahoo.com/mrss) has never been supported and was just accidentally mentioned in the specification some time around July 2009.

**Comment by mishako** [comment]
@guw Any thoughts?

**Comment by guw** [comment]
Guess that means I have to live with my workaround.

**Comment by mishako** [comment]
@guw Maybe you can reach out to the developers of that system?

**Comment by guw** [comment]
I tried that. Not worth an hour of my life time.
